// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWMzms0nfFuCHJIX-VcEQS72Tkc2xJ7m0',
    appId: '1:260972891398:web:2bcd41794f20356f586287',
    messagingSenderId: '260972891398',
    projectId: 'butterfly-ott',
    authDomain: 'butterfly-ott.firebaseapp.com',
    storageBucket: 'butterfly-ott.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD--yK6PU6HEgmG_RrRPtB9R-qMubW3w9I',
    appId: '1:260972891398:android:f9933972b17ad356586287',
    messagingSenderId: '260972891398',
    projectId: 'butterfly-ott',
    storageBucket: 'butterfly-ott.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCApAenPfxDjNpV_YHnIjCg9WtgLARIb1Q',
    appId: '1:260972891398:ios:8f1b9966b02b891c586287',
    messagingSenderId: '260972891398',
    projectId: 'butterfly-ott',
    storageBucket: 'butterfly-ott.firebasestorage.app',
    iosBundleId: 'app.voltott.app',
  );

}