// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgqHFkryAI2dQf78zD0BdjVPjUzqZo8Ls',
    appId: '1:227381852653:web:aacd05e13183acd17d8fe4',
    messagingSenderId: '227381852653',
    projectId: 'chill-app-e716c',
    authDomain: 'chill-app-e716c.firebaseapp.com',
    storageBucket: 'chill-app-e716c.firebasestorage.app',
    measurementId: 'G-CC84DDWSF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDU_BUv7QOOSN7_As8AlBlaJWv6Swu5kg',
    appId: '1:227381852653:android:f8f95c6162f323d87d8fe4',
    messagingSenderId: '227381852653',
    projectId: 'chill-app-e716c',
    storageBucket: 'chill-app-e716c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-QKuPGLowftKrkApBhcQ_Cf2jnxtz2-o',
    appId: '1:227381852653:ios:7ca5f38960384bd57d8fe4',
    messagingSenderId: '227381852653',
    projectId: 'chill-app-e716c',
    storageBucket: 'chill-app-e716c.firebasestorage.app',
    androidClientId: '227381852653-av03d0k2decs4gpql2poc7g1b8sqv9ma.apps.googleusercontent.com',
    iosClientId: '227381852653-9gps57rdanb5jh9r52ed7fmhh6qicmf1.apps.googleusercontent.com',
    iosBundleId: 'com.chill.entertainment',
  );

}